# Generated by Django 3.0.6 on 2020-05-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='description',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='image',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
