# Generated by Django 3.0.6 on 2020-05-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='users',
            new_name='user',
        ),
    ]
