# Generated by Django 3.0.6 on 2020-05-07 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Billing'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.CharField(default='images/mario-bros-nintendo-nes.jpg', max_length=999),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Payment'),
        ),
    ]
