# Generated by Django 3.0.6 on 2020-05-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
