# Generated by Django 3.0.5 on 2020-05-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200513_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.CharField(default='https://f0.pngfuel.com/png/782/114/profile-icon-png-clip-art.png', max_length=999),
        ),
    ]
