# Generated by Django 3.0.5 on 2020-05-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200513_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='exp_date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
