# Generated by Django 3.0.5 on 2020-05-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetails',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
