# Generated by Django 3.0.6 on 2020-05-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
