# Generated by Django 3.0.6 on 2020-05-06 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='console_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consoles.Console'),
        )
    ]
