# Generated by Django 3.0.6 on 2020-05-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200511_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.CharField(max_length=6),
        ),
    ]
