# Generated by Django 3.0.5 on 2020-05-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='image',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
