# Generated by Django 3.0.6 on 2020-05-11 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200511_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Billing'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Payment'),
        ),
    ]
