# Generated by Django 3.0.5 on 2020-05-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200511_1758'),
        ('orders', '0005_auto_20200511_1643'),
    ]

    operations = [
    ]
