# Generated by Django 3.0.5 on 2020-05-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200513_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvc',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_date',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='temporarypayment',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='temporarypayment',
            name='cvc',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='temporarypayment',
            name='exp_date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
